name = "SingleFactorANOVA"
uuid = "a40b7639-6cd6-46e2-b7f4-d3892dcee6c6"
authors = ["Matt Helm <mthelm85@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"

[compat]
Distributions = "0.25"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
